SOLUTIONS:

https://eduxir.com/study-material/ncert-solutions/class-11/information-practices/introduction-to-numpy/case-study-solutions/

#Mounting Drive

In [75]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#Code

In [ ]:
import numpy as np
import pandas as pd

In [76]:
#1.
iris = np.genfromtxt('/content/drive/MyDrive/STUDY2/DATA ANALYSIS LAB/IRIS_PROBLEM/iris1.csv', skip_header=1, delimiter=',', dtype=float)

In [81]:
#2. Dropping column whose index=4 from array iris
iris = np.delete(iris, 4, axis=1)

In [82]:
#3.print shape, dimensions and size
print(iris.shape)
print(iris.size)
print(iris.ndim)

(149, 4)
596
2


In [85]:
#4. Splitting iris into 2d arrays
iris1,iris2,iris3 = np.array_split(iris, 3)

#5. Print the arrays
print(iris1,'\n\n',iris2,'\n\n',iris3)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]] 

 [[6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.

In [86]:
#6.
header=np.array(["sepal length","sepal width","petal length","petal width","species No"])
#7.
print(header)

['sepal length' 'sepal width' 'petal length' 'petal width' 'species No']


In [87]:
#8.
iris_max=iris.max(axis=0).round(2)
iris_min=iris.min(axis=0).round(2)
iris_avg=iris.mean(axis=0).round(2)
iris_std=iris.std(axis=0).round(2)

In [88]:
#9.
iris1_max=iris1.max(axis=0).round(2)
iris1_min=iris1.min(axis=0).round(2)
iris1_avg=iris1.mean(axis=0).round(2)
iris1_std=iris1.std(axis=0).round(2)

iris2_max=iris2.max(axis=0).round(2)
iris2_min=iris2.min(axis=0).round(2)
iris2_avg=iris2.mean(axis=0).round(2)
iris2_std=iris2.std(axis=0).round(2)

iris3_max=iris3.max(axis=0).round(2)
iris3_min=iris3.min(axis=0).round(2)
iris3_avg=iris3.mean(axis=0).round(2)
iris3_std=iris3.std(axis=0).round(2)

In [89]:
#10.

columns = ["Iris setosa", "Iris virginica", "Iris versicolor"]
rows = ["sepal length", "sepal width", "petal length", "petal width"]

df = pd.DataFrame(columns=columns, index=rows)

df.loc["sepal length","Iris setosa"]=iris1_min[0] > iris_min[0]
df.loc["sepal length","Iris virginica"]=iris2_min[0] > iris_min[0]
df.loc["sepal length","Iris versicolor"]=iris3_min[0] > iris_min[0]

df.loc["sepal width","Iris setosa"]=iris1_min[1] > iris_min[1]
df.loc["sepal width","Iris virginica"]=iris2_min[1] > iris_min[1]
df.loc["sepal width","Iris versicolor"]=iris3_min[1] > iris_min[1]

df.loc["petal length","Iris setosa"]=iris1_min[2] > iris_min[2]
df.loc["petal length","Iris virginica"]=iris2_min[2] > iris_min[2]
df.loc["petal length","Iris versicolor"]=iris3_min[2] > iris_min[2]

df.loc["petal width","Iris setosa"]=iris1_min[3] > iris_min[3]
df.loc["petal width","Iris virginica"]=iris2_min[3] > iris_min[3]
df.loc["petal width","Iris versicolor"]=iris3_min[3] > iris_min[3]


#or
'''
# Loop through rows and columns to fill the DataFrame
for row in rows:
    iris_min_value = globals()["iris_min"][rows.index(row)]  # Get the corresponding iris_min value

    for column in columns:
        iris_min_column = globals()["iris{}_min".format(columns.index(column) + 1)][rows.index(row)]
        condition = iris_min_column > iris_min_value
        df.loc[row, column] = condition
'''

df

'\n# Loop through rows and columns to fill the DataFrame\nfor row in rows:\n    iris_min_value = globals()["iris_min"][rows.index(row)]  # Get the corresponding iris_min value\n\n    for column in columns:\n        iris_min_column = globals()["iris{}_min".format(columns.index(column) + 1)][rows.index(row)]\n        condition = iris_min_column > iris_min_value\n        df.loc[row, column] = condition\n'

In [90]:
#11, 12, 13.

iris_avg=np.array([(iris1_avg[1]>iris2_avg[1]),
                   (iris1_avg[2]>iris2_avg[2]),
                   (iris1_avg[3]>iris2_avg[3])])

print(iris_avg)

[ True False False]


In [91]:
#14.
np.savetxt('/content/drive/MyDrive/STUDY2/DATA ANALYSIS LAB/IRIS_PROBLEM/IrisMeanValues.txt',iris_avg,delimiter=',',fmt='%.2f')

In [92]:
#15.
# Find the maximum number of columns among the arrays
max_columns = max(iris_max.shape[0], iris_avg.shape[0], iris_min.shape[0])

# Pad the shorter arrays with NaN values to match the maximum number of columns
iris_max_padded = np.pad(iris_max, (0, max_columns - iris_max.shape[0]), constant_values=np.nan)
iris_avg_padded = np.pad(iris_avg, (0, max_columns - iris_avg.shape[0]), constant_values=np.nan)
iris_min_padded = np.pad(iris_min, (0, max_columns - iris_min.shape[0]), constant_values=np.nan)

# Stack the padded arrays vertically to create a 2D array
iris_stat = np.vstack((iris_max_padded, iris_avg_padded, iris_min_padded))

fmt = '%.2f'

np.savetxt('/content/drive/MyDrive/STUDY2/DATA ANALYSIS LAB/IRIS_PROBLEM/IrisStat.txt',
           iris_stat, delimiter=',', fmt=fmt)
