#LINK:
## http://courses.rvrjc.ac.in/moodle/pluginfile.php/43496/mod_resource/content/1/numpy-basics.html

In [1]:
import numpy as np

### Creating arrays

In [2]:
a=np.zeros(10,dtype=int)
print(a)
print("\n")

a=np.ones((2,3),dtype=float)
print(a)
print("\n")

a=np.full((3,4),22)
print(a)
print("\n")

a=np.eye(4,4)
print(a)
print("\n")

a=np.arange(0,20,3)
print(a)
print("\n")

a=np.linspace(0,1,5)
print(a)
print("\n")

#uniformly distrbuted random values
a=np.random.random((2,2))
print(a)
print("\n")

#normally distributed random values
a=np.random.normal(0,1,(2,3))
print(a)
print("\n")

#random integers
a=np.random.randint(2,20,(2,2))
print(a)
print("\n")

#create an uninitialized array of 3 elements
a=np.empty(3)
print(a)
print("\n")

l=[3,6,9,1]
a=np.array(l)
print(a)
print("\n")

l=[1,2.,4,7,9]
a=np.array(l)
print(a)
print("\n")

#Nested sequences
l1=[2,3,4]
l2=[1,2,3]
a=np.array((l1,l2))
print(a)

[0 0 0 0 0 0 0 0 0 0]


[[1. 1. 1.]
 [1. 1. 1.]]


[[22 22 22 22]
 [22 22 22 22]
 [22 22 22 22]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[ 0  3  6  9 12 15 18]


[0.   0.25 0.5  0.75 1.  ]


[[0.71338412 0.43183536]
 [0.26773459 0.76147032]]


[[ 0.61126279  0.72148818  0.19355325]
 [-0.47124037 -0.54341649 -0.83446742]]


[[16 16]
 [ 3  8]]


[0.  0.5 1. ]


[3 6 9 1]


[1. 2. 4. 7. 9.]


[[2 3 4]
 [1 2 3]]


In [3]:
#Creating similar arrays
a1 = np.array([1, 2, 3], dtype=np.float64)
print(a1)
print(a1.dtype)

a2 = np.array([1., 2, 3], dtype=np.int32)
print(a2,a2.dtype)

#Explicitly convert or cast an array from one dtype to another using ndarray’s astype method
a3=a2.astype(np.float64)
print(a3,a3.dtype)

numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)
print(numeric_strings)

print(a3.astype(a2.dtype))

[1. 2. 3.]
float64
[1 2 3] int32
[1. 2. 3.] float64
[b'1.25' b'-9.6' b'42']
[1 2 3]


In [4]:
#Numpy array attributes
a=np.random.randint(20,size=(2,4))
print(a)
print('ndim',a.ndim,'shape=',a.shape,a.size)

[[ 4  3 12 14]
 [18  0 16  2]]
ndim 2 shape= (2, 4) 8


In [5]:
#Arithmetic operations with NumPy arrays
a = np.array([[1., 2., 3.], [4., 5., 6.]])
print(a+a)
print(a*a)
print(1/a)
print(a-a)
print(a+10)
print(a*10)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[11. 12. 13.]
 [14. 15. 16.]]
[[10. 20. 30.]
 [40. 50. 60.]]


In [6]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])
b = np.array([[1., 2.], [3.,4.],[4., 5.]])

print(a@b)
print(np.dot(a,b))
print(np.matmul(a,b))

[[19. 25.]
 [43. 58.]]
[[19. 25.]
 [43. 58.]]
[[19. 25.]
 [43. 58.]]


### Basic Indexing and Slicing

In [7]:
# array slices are views on the original array
#This means that the data is not copied, and any modifications
#to the view will be reflected in the source array.

#if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is
#propagated to the entire selection

a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a[1])
print(a[1,2], a[1][2])

temp=a[0].copy()
a[0]=66
print(a)

a[0]=temp
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
6 6
[[66 66 66]
 [ 4  5  6]
 [ 7  8  9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#slicing
# There are many ways you may want to select a subset of your data or individual elements
a=np.arange(1,10)
print(a)
print(a[3:8])

a2=a[3:8]

print(a,a2)

a2[:]=88
print(a2,a)

print("_____________")
a=np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[9,8,7]]])
print(a)
print('*****')
print(a[0])
print(a[0,1])
print(a[0,1,2])
print('*****')
print(a[1])

a=np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
print(a)
print(a[:2,:1])
print(a[1,:2])
print(a[2,:1])
###
b=a[:,1]
print("columns")
print(b,b.size, b.shape)
c=a[:,:2]
print(c,c.size, c.shape,c.ndim)
c=a[:,2]
print(c,c.size, c.shape,c.ndim)
d=a[:,2:]
print(d,d.size,d.shape,d.ndim)

[1 2 3 4 5 6 7 8 9]
[4 5 6 7 8]
[1 2 3 4 5 6 7 8 9] [4 5 6 7 8]
[88 88 88 88 88] [ 1  2  3 88 88 88 88 88  9]
_____________
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 8 7]]]
*****
[[1 2 3]
 [4 5 6]]
[4 5 6]
6
*****
[[7 8 9]
 [9 8 7]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]]
[4 5]
[7]
columns
[2 5 8] 3 (3,)
[[1 2]
 [4 5]
 [7 8]] 6 (3, 2) 2
[3 6 9] 3 (3,) 1
[[3]
 [6]
 [9]] 3 (3, 1) 2


### Boolean Indexing

In [9]:
names = np.array(['Bob', 'Joe', 'Will', 'tttt'])
data = np.random.randn(4, 4)
print(names,names.dtype,data,data.dtype)
print('\n')
print(names == 'Bob')
print('\n')
print(data[names=='Bob'])
print('\n')
print(names != 'Bob')
print('\n')
mask = (names == 'Bob') | (names == 'Will')
print('mask=   ',mask)
print('\n')
print(data[data>0])
#set all of the negative values in data to 0 we need only do
data[data<0]=0
print(data)
#The boolean array must be of the same length as the axis it’s indexing

['Bob' 'Joe' 'Will' 'tttt'] <U4 [[-0.10803675 -1.77845321 -0.01284343  0.34557449]
 [-2.05961845 -1.1388764  -0.70302318 -0.99707284]
 [-1.1331531   0.80979045 -1.84127471 -0.81123156]
 [-1.74901656 -0.67147972  1.02344174 -1.15959301]] float64


[ True False False False]


[[-0.10803675 -1.77845321 -0.01284343  0.34557449]]


[False  True  True  True]


mask=    [ True False  True False]


[0.34557449 0.80979045 1.02344174]
[[0.         0.         0.         0.34557449]
 [0.         0.         0.         0.        ]
 [0.         0.80979045 0.         0.        ]
 [0.         0.         1.02344174 0.        ]]


### Fancy Indexing - describes indexing using integer arrays

In [10]:
a=np.empty((8,4))
for i in range(8):
    a[i]=i
print(a)
print('\n*******\n')
print(a[[4,1,6,0]])

#using negative indices
print(a[[-1,-3,-6]])

#Multiple index arrays - selects a one dimensional array of elements corresponding to each tuple of indices.
#regardless of no of dimensions of the array, the result is one-dimensional
a= np.arange(32).reshape(8,4)

print(a)
print('\n\n -----')
print(a[[1,5,7,2],[0,3,1,2]])
print('/n******\n\n')
#slicing
a1=a[[1,5,7,2]][:,[0,3,1,2]]
print(a1)

#Fancy indexing, unlike slicing, always copies the data into a new array.

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]

*******

[[4. 4. 4. 4.]
 [1. 1. 1. 1.]
 [6. 6. 6. 6.]
 [0. 0. 0. 0.]]
[[7. 7. 7. 7.]
 [5. 5. 5. 5.]
 [2. 2. 2. 2.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


 -----
[ 4 23 29 10]
/n******


[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


### Matrix operations

In [11]:
a=np.array([[1,2],[3,4],[5,6]])
print('insert operation axis=0  \n')
print(np.insert(a,1,[4,9],axis=0))
print('\ninsert operation axis=1 \n')
print(np.insert(a,1,[9],axis=1))

insert operation axis=0  

[[1 2]
 [4 9]
 [3 4]
 [5 6]]

insert operation axis=1 

[[1 9 2]
 [3 9 4]
 [5 9 6]]


In [12]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[11,22],[33,44],[55,66]])
c=a+b
d=np.append(a,b)
print(c,type(c),np.shape(c))
print(d, type(d),np.shape(d))
z=np.concatenate((a,b))
print(z)

[[12 24]
 [36 48]
 [60 72]] <class 'numpy.ndarray'> (3, 2)
[ 1  2  3  4  5  6 11 22 33 44 55 66] <class 'numpy.ndarray'> (12,)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [11 22]
 [33 44]
 [55 66]]


###Broadcasting


In [17]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([1,2,3,4])
c=7
d=np.array([8])
print(a.shape,b.shape,d.shape)
#print(a+b)
print(a+c)
print(a+d)

(3, 2) (4,) (1,)
[[ 8  9]
 [10 11]
 [12 13]]
[[ 9 10]
 [11 12]
 [13 14]]


In [18]:
import numpy as np
#a=np.array([[1,2],[3,4],[5,6]])
a=np.array([1,2,3,4])
#b=np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8]])
#b=np.array([[1],[2],[3]])
b=np.array([[1],[2],[3],[4]])
print(a.ndim,b.ndim)
print(a.shape,b.shape)
print(a+b)

1 2
(4,) (4, 1)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


### Universal functions:
ufunc, is a function that performs element-wise
operations on data in ndarrays #think of them as fast vectorized wrappers for simple functions that take one or more scalar #values and produce one or more scalar results

In [13]:
#unary ufunc
a=np.arange(10)
print(a)
print(np.sqrt(a))

print(np.exp(a))

#binary ufunc
#np.maximum computes element wise maximum
#fmax ignores NaN
a=np.random.randn(8)
b=np.random.randn(8)
print(a)
print(b)
print(np.maximum(a,b))

#modf returns the fractional and integral parts of floating point array
a=np.random.randn(5)*5
print(a)
rem,whole=np.modf(a)
print(rem)
print(whole)

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 1.05573642 -0.79403465 -0.1550624   0.80978691  1.74291254 -0.26507865
  0.00421013  1.81234406]
[ 0.57612029  0.34931122 -1.62506024 -1.76745725 -0.51591525 -0.89647269
  1.33423433 -1.54084135]
[ 1.05573642  0.34931122 -0.1550624   0.80978691  1.74291254 -0.26507865
  1.33423433  1.81234406]
[-0.27212132 -4.06505297  2.03995038  1.88620296  1.46611149]
[-0.27212132 -0.06505297  0.03995038  0.88620296  0.46611149]
[-0. -4.  2.  1.  1.]


###mathematical and statistical methods
use aggregations like sum, mean and std either by calling the array instance method or using the top-level numPy function.

In [14]:
a=np.random.randn(5,4)
print(a.mean())
print(np.mean(a))
print(np.sum(a))

# mean and sum take an optyional axis argument that computes the statistic over the given axis, resulting in an array with one fewer dimension
a.mean(axis=1)
a.sum(axis=0)

a = np.array([1,0,2,-3,6,8,4,7])
b = np.array([[3,6],[4,2]])
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(b.mean(axis=0))
print(a.std())
print(b.std(axis=0))

-0.2692627586940452
-0.2692627586940452
-5.385255173880904
8
-3
25
3.125
[3.5 4. ]
3.550968177835448
[0.5 2. ]


###splitting arrays

In [19]:
import numpy as np
a=np.arange(1,25).reshape(12,2)
print(a, a.ndim,a.size,a.shape)
print('\n  vsplit  \n')
#hsplit -  split into equally shaped arrays
print(np.vsplit(a,3))

print('\n  vsplit  \n')
print(np.vsplit(a,(3,4)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]] 2 24 (12, 2)

  vsplit  

[array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]]), array([[17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])]

  vsplit  

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[7, 8]]), array([[ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])]


###Stacking arrays

In [20]:
a1=np.array([[1,1],[2,2]])
a2=np.array([[3,3],[4,4]])
print(a1,a2)
print('\n vstack \n')
print(np.vstack((a1,a2)))
print('\n hstack \n')
print(np.hstack((a1,a2)))

[[1 1]
 [2 2]] [[3 3]
 [4 4]]

 vstack 

[[1 1]
 [2 2]
 [3 3]
 [4 4]]

 hstack 

[[1 1 3 3]
 [2 2 4 4]]


###Sorting

In [21]:
a=np.array([10,6,3,8,2,1,7,5])
print(np.sort(a))
a=np.array([[1,4],[3,2]])
print(a)
print('\n  axis = None \n')

print(np.sort(a,axis=None))

print('\n  axis = 0 \n')
print(np.sort(a))

print('\n  axis = 1 \n')
b=np.array([[9,4],[13,2]])
print('\n array \n')
print(b,'\n')
print(np.sort(b,axis=1))

[ 1  2  3  5  6  7  8 10]
[[1 4]
 [3 2]]

  axis = None 

[1 2 3 4]

  axis = 0 

[[1 4]
 [2 3]]

  axis = 1 


 array 

[[ 9  4]
 [13  2]] 

[[ 4  9]
 [ 2 13]]


###Reversing an array

In [22]:
a=[9,2,5,1,8,4]
print(np.flip(a))
#Reverse only rows or only columns
a=[[3,9,5],[6,2,4]]
print(np.flip(a))
print(np.flip(a,axis=0))
print(np.flip(a,axis=1))

[4 8 1 5 2 9]
[[4 2 6]
 [5 9 3]]
[[6 2 4]
 [3 9 5]]
[[5 9 3]
 [4 2 6]]


###Flattening an Array

In [23]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a.flatten()

print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


###Searching arrays

In [43]:
#linear search
a=np.array([3,4,23,2,1,88,7])
print(np.where(a==4),"\n")
print(a[np.where(a>5)],"\n")

#Searchsorted - performs a binary search and returns the index
#where the specified value would be inserted
print(np.searchsorted(a,88))
print(np.searchsorted(a,88,side='right'))
print(np.searchsorted(a,88,side='left'))

'''
In this code, you're using the NumPy library to perform binary searches using the
np.searchsorted function on a NumPy array a which contains the values [3, 4, 23, 2, 1, 88, 7].

The first line (print(np.searchsorted(a, 88))) performs a binary search for the value 88 in the array a.
It returns the index where the value 88 would be inserted to maintain the sorted order of the array.
 In this case, the output will be 5, which means if you were to insert 88 into the array a while keeping it sorted,
  it would be placed at index 5.

The second line (print(np.searchsorted(a, 88, side='right'))) performs a binary search for the value 88,
 similar to the first line. However, the side parameter is set to 'right'.
 This parameter determines the behavior when multiple occurrences of the search value are found.
 In this case, it returns the index where the rightmost occurrence of the value 88 could be inserted while maintaining sorted order.
 If there are multiple occurrences of 88, this will return the index just after the last occurrence. If there's only one occurrence,
  it behaves the same as the first line, and the output will still be 5.

The third line (print(np.searchsorted(a, 88, side='left'))) also performs a binary search for the value 88,
but this time the side parameter is set to 'left'.
 This returns the index where the leftmost occurrence of the value 88 could be inserted while maintaining sorted order.
 If there are multiple occurrences of 88, this will return the index of the first occurrence. If there's only one occurrence,
  it behaves the same as the first line, and the output will still be 5.
'''

(array([1]),) 

[23 88  7] 

5
7
5


"\nIn this code, you're using the NumPy library to perform binary searches using the \nnp.searchsorted function on a NumPy array a which contains the values [3, 4, 23, 2, 1, 88, 7].\n\nThe first line (print(np.searchsorted(a, 88))) performs a binary search for the value 88 in the array a. \nIt returns the index where the value 88 would be inserted to maintain the sorted order of the array.\n In this case, the output will be 5, which means if you were to insert 88 into the array a while keeping it sorted,\n  it would be placed at index 5.\n\nThe second line (print(np.searchsorted(a, 88, side='right'))) performs a binary search for the value 88,\n similar to the first line. However, the side parameter is set to 'right'. \n This parameter determines the behavior when multiple occurrences of the search value are found. \n In this case, it returns the index where the rightmost occurrence of the value 88 could be inserted while maintaining sorted order. \n If there are multiple occurrences o

In [42]:
#np.where
boo1=np.array([True,False,True])
boo2=np.array([True,False,False])
one=np.array([2,6,5])
two=np.array([5,3,6])
res=np.where(boo1 & boo2,0,
             np.where(boo1,1,
                      np.where(boo2,2,3)
                      )
             )
print(res)

[0 3 1]


###Immutable array

In [32]:
#how to make numpy array immutable
a=np.array([1,2,3,4,5])
a[0]=99
print(a)
a.setflags(write=False)
'''
a[0]=88
print(a)

OUTPUT:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-acf3e2837f3e> in <cell line: 6>()
      4 print(a)
      5 a.setflags(write=False)
----> 6 a[0]=88
      7 print(a)

ValueError: assignment destination is read-only
'''


[99  2  3  4  5]


'\na[0]=88\nprint(a)\n\nOUTPUT:\n---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\n<ipython-input-31-acf3e2837f3e> in <cell line: 6>()\n      4 print(a)\n      5 a.setflags(write=False)\n----> 6 a[0]=88\n      7 print(a)\n\nValueError: assignment destination is read-only\n'

###Structured arrays

In [33]:
#structured arrays
x=np.array([('Rama',12,6),('sita',10,7)],
           dtype=[('name','<U10'),('age','i4'),('cgpa','f4')])
print(x)
x
print(x['name'])

'''
x = np.array([...], dtype=[...]): This creates a NumPy array x with structured data.
 The structured data type is specified using the dtype parameter.
  The data consists of tuples containing information about individuals,
  where each tuple has three fields: 'name', 'age', and 'cgpa'.

'name', '<U10' indicates that the 'name' field
is of Unicode string type with a maximum length of 10 characters.

'age', 'i4' indicates that the 'age' field
 is of integer type with a size of 4 bytes (32 bits).

'cgpa', 'f4' indicates that the 'cgpa' field
 is of floating-point type with a size of 4 bytes (32 bits).
'''

[('Rama', 12, 6.) ('sita', 10, 7.)]
['Rama' 'sita']


###Date

In [40]:
from datetime import datetime as date
x=date.fromisoformat('2019-12-04')
print(x)
print(date.today())
print(date.time(x))
print(date.time(date.today()))

2019-12-04 00:00:00
2023-08-28 08:09:29.230458
00:00:00
08:09:29.231933


###Files

In [29]:
a = np.array([1, 2, 3, 4, 5, 6])
np.save('filename', a)
b = np.load('filename.npy')
print(b,type(b))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [26]:
#Save a NumPy array as a plain text file like a .csv or .txt file with np.savetxt.
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('new_file.csv', a)
b=np.loadtxt('new_file.csv')
print(b,type(b))

[1. 2. 3. 4. 5. 6. 7. 8.] <class 'numpy.ndarray'>


In [30]:
#Loading Arrays from Files
import numpy as np
sdata = np.loadtxt('new_file.csv', skiprows=1, delimiter=' ')
print(sdata)

[2. 3. 4. 5. 6. 7. 8.]
